name: Build and test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        compiler: [clang-3.9, clang-4.0, clang-5.0, clang-6.0, clang-7, clang-8, clang-9, clang-10, g++-4.8, g++-5, g++-6, g++-7, g++-8]

    runs-on: ${{matrix.os}}

    steps:
      - name: Install dependencies
        run: sudo apt install build-essential libasound2-dev libqt5sql5-sqlite libqt5svg5-dev pkg-config qt5-default ${{matrix.compiler}}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure
        run: qmake -spec linux-`echo ${{matrix.compiler}} | cut -d'-' -f1`

      - name: Build
        run: make

      - name: Test
        run: make check
