name: Build and test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        build_type:
          - Debug
          - Release
        compiler: [{
            pkg: "clang",
            version: "3.9",
            cc: "clang",
            cxx: "clang++",
          }, {
            pkg: "clang",
            version: "4.0",
            cc: "clang",
            cxx: "clang++",
          }, {
            pkg: "clang",
            version: "5.0",
            cc: "clang",
            cxx: "clang++",
          }, {
            pkg: "clang",
            version: "6.0",
            cc: "clang",
            cxx: "clang++",
          }, {
            pkg: "clang",
            version: "7",
            cc: "clang",
            cxx: "clang++",
          }, {
            pkg: "clang",
            version: "8",
            cc: "clang",
            cxx: "clang++",
          }, {
            pkg: "clang",
            version: "9",
            cc: "clang",
            cxx: "clang++",
          }, {
            pkg: "clang",
            version: "10",
            cc: "clang",
            cxx: "clang++",
          }, {
            pkg: "g++",
            version: "4.8",
            cc: "gcc",
            cxx: "g++",
          }, {
            pkg: "g++",
            version: "5",
            cc: "gcc",
            cxx: "g++",
          }, {
            pkg: "g++",
            version: "6",
            cc: "gcc",
            cxx: "g++",
          }, {
            pkg: "g++",
            version: "7",
            cc: "gcc",
            cxx: "g++",
          }, {
            pkg: "g++",
            version: "8",
            cc: "gcc",
            cxx: "g++",
        }]

    env:
      PKG: ${{ matrix.compiler.pkg }}-${{ matrix.compiler.version }}
      CC: ${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}
      CXX: ${{ matrix.compiler.cxx }}-${{ matrix.compiler.version }}

    runs-on: ${{matrix.os}}

    steps:
      - name: Install dependencies
        run: sudo apt install cmake libasound2-dev libqt5sql5-sqlite libqt5svg5-dev pkg-config qt5-default $PKG

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build .

      - name: Test
        run: make test
